# Generated by Django 5.1.2 on 2024-10-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_decelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='decelements',
            name='quote',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='quote',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
