# Generated by Django 5.1.2 on 2024-10-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event'),
        ('eventusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.IntegerField(choices=[(2, 'EVENT_PROCESSED'), (3, 'EVENT_DELIVERED'), (4, 'EVENT_REJECTED')], default=1)),
                ('delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='eventusers.users')),
            ],
        ),
        migrations.CreateModel(
            name='eventbookeditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestcount', models.IntegerField(default=10)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_events', to='events.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_events', to='event_orders.eventcart')),
            ],
        ),
    ]
