# Generated by Django 5.2.7 on 2025-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcart',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='eventbookeditem',
            name='guestcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventcart',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='eventcart',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'In Cart'), (1, 'Booked'), (2, 'Processed'), (3, 'Delivered'), (4, 'Rejected')], default=0),
        ),
    ]
